print("oii💕")
a=True
b=False
c=True
print(a and a)
print(b and b)
print(not c)
print(not b)
print(not a)
print(a and b)
print(b and c)
print(a or c)
print(b or c)
print(c or a)
print(c or b)
print(c or c)
print(b or b)
nome="Maria Clara"
print(nome[10])
print(nome[0:0])
print(nome[-1:-2])
print(nome[-11:])
print(nome.startswith("Maria"))
print(nome.endswith("Clara"))
print("Clara".replace("C" , "Ca"))
print(len("Maria Clara"))
print(nome)
print(nome.strip())
print(nome.lower())
print(nome.upper())